fix: staticcheck fixes and linter warnings suppressed
fix the warnings from staticheck based on the following.
silencing the strings.Title as there is lint comment previously present

$ staticcheck ./...
report/export.go:70:9: error strings should not be capitalized (ST1005)
report/export.go:75:9: error strings should not be capitalized (ST1005)
report/import.go:31:15: error strings should not be capitalized (ST1005)
report/import.go:36:15: error strings should not be capitalized (ST1005)
report/import.go:50:15: error strings should not be capitalized (ST1005)
report/import.go:54:15: error strings should not be capitalized (ST1005)
tui/actions.go:195:3: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019)
tui/marked.go:58:6: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019)